os: linux
dist: bionic
language: node_js
node_js:
  - 'stable'
  - '12'
  - '11'
  - '10'
  - '9'
  - '8'
  - '6'
  - '4'

jobs:
  include:
    - name: Run browser tests with airtap
      node_js: stable
      script: npm run test:browsers
      addons:
        sauce_connect: true
        hosts:
          - airtap.local
